### ISSUE TITLE
No such file or directory error on every delta index

### ISSUE THREAD

**Issue by mikemerritt** [agibralter/ts-resque-delta#29]
All of my resque delta jobs are failing with this error.

```
No such file or directory @ unlink_internal - /home/deploy/myapp/releases/20150701182652/db/sphinx/ts-index_name_delta.tmp
```

This works locally but fails when the app is deployed to a remote server via capistrano.

**Comment by pat** [comment]
Hi Mike

Can you supply the full stacktrace? Also, what settings do you have in `config/thinking_sphinx.yml` for this environment (production, I presume)?

**Comment by mikemerritt** [comment]
@pat 

It's a remote development server so the app is running in development mode.

Stacktrace

```
/usr/local/lib/ruby/2.2.0/fileutils.rb:1450:in `unlink'
/usr/local/lib/ruby/2.2.0/fileutils.rb:1450:in `block in remove_file'
/usr/local/lib/ruby/2.2.0/fileutils.rb:1455:in `platform_support'
/usr/local/lib/ruby/2.2.0/fileutils.rb:1449:in `remove_file'
/usr/local/lib/ruby/2.2.0/fileutils.rb:793:in `remove_file'
/usr/local/lib/ruby/2.2.0/fileutils.rb:571:in `block in rm'
/usr/local/lib/ruby/2.2.0/fileutils.rb:570:in `each'
/usr/local/lib/ruby/2.2.0/fileutils.rb:570:in `rm'
/home/deploy/myapp/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/guard/file.rb:24:in `unlock'
/home/deploy/myapp/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/guard/files.rb:18:in `each'
/home/deploy/myapp/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/guard/files.rb:18:in `ensure in call'
/home/deploy/myapp/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/guard/files.rb:18:in `call'
/home/deploy/myapp/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/guard/files.rb:3:in `call'
/home/deploy/myapp/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/controller.rb:6:in `index'
/home/deploy/myapp/shared/bundle/ruby/2.2.0/gems/thinking-sphinx-3.1.3/lib/thinking_sphinx/deltas/index_job.rb:7:in `perform'
/home/deploy/myapp/shared/bundle/ruby/2.2.0/gems/ts-resque-delta-2.0.0/lib/thinking_sphinx/deltas/resque_delta/delta_job.rb:12:in `perform'
```

Config

``` yaml
development:
  pid_file: "<%= Rails.root %>/tmp/pids/searchd.pid"
  indices_location: "<%= Rails.root %>/db/sphinx"
  configuration_file: "<%= Rails.root %>/config/development.sphinx.conf"
  binlog_path: "<%= Rails.root %>/tmp/binlog"
  min_infix_len: 1
production:
  pid_file: "<%= Rails.root %>/tmp/pids/searchd.pid"
  indices_location: "<%= Rails.root %>/db/sphinx"
  configuration_file: "<%= Rails.root %>/config/production.sphinx.conf"
  binlog_path: "<%= Rails.root %>/tmp/binlog"
  min_infix_len: 1
```

**Comment by pat** [comment]
I'm not entirely sure if it's related, but the first thing I'd change is to remove <%= Rails.root %> from each of those file/path settings and hard-code an actual path in there, and have them be in the shared directory.

``` yml
pid_file: "/home/deploy/myapp/shared/tmp/pids/searchd.pid"
indices_location: "/home/deploy/myapp/shared/db/sphinx"
configuration_file: "/home/deploy/myapp/shared/config/development.sphinx.conf"
binlog_path: "/home/deploy/myapp/shared/tmp/binlog"
```

I know that doesn't feel particularly elegant, but you do not want those files/paths tied to a particular deploy version - otherwise you'll need to re-index and restart on every deploy. This could also be why the lock files for indexing are disappearing…
